# This is a basic workflow to help you get started with Actions

name: sample-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [push]
jobs:
  # This workflow contains a single job called "build"
  explore-first-github-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: 
          echo This job was automatically triggered by ${{github.event_name}} event.
          echo This job is running now on  ${{runner.os}} hosted by Github.
          echo The name of your bracnh is  ${{github.ref}} and name of repository is ${{github.repository}}
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - run: echo repository ${{github.repository}} has been cloned to runner
      - run: echo The workflow is ready now to test your code in runner
      - name: List all files on runner
        run: 
          ls ${{github.workspace}}
      - run: echo Job status is ${{job.status}}
